name: Build executable with PyInstaller
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build the executables
      run: pyinstaller run.py -F -n VRCSDK-Patcher
    - name: Upload the executables
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: dist/*.exe
